server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/haircareAi
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  key:
    signing-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

  image:
    storage:
      path: C:/java_projects/FYP/backend/images/



#  redis:
#    uri: redis://default:ptcPM7P8Bg6nI67BOUwgWVnma8bdRVXU@redis-10458.c264.ap-south-1-1.ec2.redns.redis-cloud.com:10458

  #    host: localhost
#    port: 6379
#    host: redis-10458.c264.ap-south-1-1.ec2.redns.redis-cloud.com
#    port: 10458
#    password: ptcPM7P8Bg6nI67BOUwgWVnma8bdRVXU
#


  mail:
    host: smtp.gmail.com    #//
    port: 587
    username: muhammadsaadoo303@gmail.com
    password: mnhh tqkb uego fnio
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true







#//root package

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard: TRACE


#for whole package?
#logging:
#  level:
#    root: info



#root:off

#  servlet:
#    context-path: /e-commerce


#we can use xml for seperate of concerns..........................

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard:
#          Services:
#            CategoryService: TRACE
