server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:35073/railway
    username: postgres
    password: eDjRedFyooFRoqBgmoCnAKbrtkkwKaPF
    driver-class-name: org.postgresql.Driver


#    datasource:
#      url: jdbc:postgresql://127.0.0.1:10000/haircareai_340?sslmode=prefer
#      username: haircareai_340
#      password: o2H_FBX_A4O9wcFy0MBUZ1Oflm2jrCXEa8ntPIgOf8JAHpfa_HvbIEC6dw6iJ10R
#      driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
#      idle-timeout: 30000
#      max-lifetime: 60000
#      postgres://haircareai_340:o2H_FBX_A4O9wcFy0MBUZ1Oflm2jrCXEa8ntPIgOf8JAHpfa_HvbIEC6dw6iJ10R
#      @haircareai-340.postgresql.b.osc-fr1.scalingo-dbs.com:30778/haircareai_340?sslmode=prefer
#    .postgres://haircareai_340:o2H_FBX_A4O9wcFy0MBUZ1Oflm2jrCXEa8ntPIgOf8JAHpfa_HvbIEC6dw6iJ10R@haircareai-340.postgresql.b.osc-fr1.scalingo-dbs.com:30778/haircareai_340?sslmode=prefer


#    a postgres://haircareai_6210:xXH49dOimE7v8KzNaEJfdFX_BX_46JAEu3ogfTtyuubbYuaSKyfO31XEuZOOJgdJ@haircareai-6210.postgresql.b.osc-fr1.scalingo-dbs.com:30632/haircareai_6210?sslmode=prefer

#    psql "postgres://haircareai_620:3IYs2RTGHiAk4QS_j2ILt7WPD1W7y9JobX6cX7rC_949uiIVFc4zKLFUomF_eDoZ@127.0.0.1:1000/"

  #//https://haircareai.osc-fr1.scalingo.io -
#  api token   tk-us-ICazmnVbVCkMSZ8YLDd8EXf-q_h_D1y6Y67iR6kzwJ5roBEg
#  scalingo login --api-token tk-us-ICazmnVbVCkMSZ8YLDd8EXf-q_h_D1y6Y67iR6kzwJ5roBEg

#  access db server
#  scalingo -a haircareai db-tunnel -i ~/.ssh/id_ed25519  SCALINGO_POSTGRESQL_URL

#  access database
#  psql -h 127.0.0.1 -p 10000 -U haircareai_620 -d haircareai_620
#  addd key
#  scalingo keys-add Laptop ~/.ssh/id_ed25519.pub

#  .https://haircareai.osc-fr1.scalingo.io



  jpa:
    flyway:
      enabled: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  key:
    signing-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

  image:
    storage:
      path: C:/java_projects/FYP/backend/images/



#  redis:
#    uri: redis://default:ptcPM7P8Bg6nI67BOUwgWVnma8bdRVXU@redis-10458.c264.ap-south-1-1.ec2.redns.redis-cloud.com:10458

  #    host: localhost
#    port: 6379
#    host: redis-10458.c264.ap-south-1-1.ec2.redns.redis-cloud.com
#    port: 10458
#    password: ptcPM7P8Bg6nI67BOUwgWVnma8bdRVXU
#


  mail:
    host: smtp.gmail.com    #//
    port: 587
    username: muhammadsaadoo303@gmail.com
    password: mnhh tqkb uego fnio
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true







#//root package

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard: TRACE


#for whole package?
#logging:
#  level:
#    root: info



#root:off

#  servlet:
#    context-path: /e-commerce


#we can use xml for seperate of concerns..........................

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard:
#          Services:
#            CategoryService: TRACE
